# Generated by Django 5.1.7 on 2025-03-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('periodic', 'Periodic'), ('preventive', 'preventive'), ('category A', 'Category A'), ('category B', 'Category B'), ('category C', 'Category C'), ('category D', 'Category D')], max_length=50)),
                ('task_desc', models.CharField(max_length=255)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=255)),
                ('equipment_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_record', to='task.equipment')),
                ('equipment_serial_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.equipment')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_record', to='task.technician')),
            ],
        ),
    ]
